name: clearstats

services:
  database:
    image: postgres:latest
    container_name: clearstats-db
    restart: always
    ports:
      - "0.0.0.0:5444:5432"
    environment:
      - POSTGRES_USER=clearstats
      - POSTGRES_PASSWORD=clearstats-pw
      - POSTGRES_DB=clearstats-db
