use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "UPPERCASE")]
pub enum CountryCode {
    ABW,
    AFG,
    AGO,
    AIA,
    ALA,
    ALB,
    AND,
    ARE,
    ARG,
    ARM,
    ASM,
    ATA,
    ATF,
    ATG,
    AUS,
    AUT,
    AZE,
    BDI,
    BEL,
    BEN,
    BES,
    BFA,
    BGD,
    BGR,
    BHR,
    BHS,
    BIH,
    BLM,
    BLR,
    BLZ,
    BMU,
    BOL,
    BRA,
    BRB,
    BRN,
    BTN,
    BVT,
    BWA,
    CAF,
    CAN,
    CCK,
    CHE,
    CHL,
    CHN,
    CIV,
    CMR,
    COD,
    COG,
    COK,
    COL,
    COM,
    CPV,
    CRI,
    CUB,
    CUW,
    CXR,
    CYM,
    CYP,
    CZE,
    DEU,
    DJI,
    DMA,
    DNK,
    DOM,
    DZA,
    ECU,
    EGY,
    ERI,
    ESH,
    ESP,
    EST,
    ETH,
    FIN,
    FJI,
    FLK,
    FRA,
    FRO,
    FSM,
    GAB,
    GBR,
    GEO,
    GGY,
    GHA,
    GIB,
    GIN,
    GLP,
    GMB,
    GNB,
    GNQ,
    GRC,
    GRD,
    GRL,
    GTM,
    GUF,
    GUM,
    GUY,
    HKG,
    HMD,
    HND,
    HRV,
    HTI,
    HUN,
    IDN,
    IMN,
    IND,
    IOT,
    IRL,
    IRN,
    IRQ,
    ISL,
    ISR,
    ITA,
    JAM,
    JEY,
    JOR,
    JPN,
    KAZ,
    KEN,
    KGZ,
    KHM,
    KIR,
    KNA,
    KOR,
    KWT,
    LAO,
    LBN,
    LBR,
    LBY,
    LCA,
    LIE,
    LKA,
    LSO,
    LTU,
    LUX,
    LVA,
    MAC,
    MAF,
    MAR,
    MCO,
    MDA,
    MDG,
    MDV,
    MEX,
    MHL,
    MKD,
    MLI,
    MLT,
    MMR,
    MNE,
    MNG,
    MNP,
    MOZ,
    MRT,
    MSR,
    MTQ,
    MUS,
    MWI,
    MYS,
    MYT,
    NAM,
    NCL,
    NER,
    NFK,
    NGA,
    NIC,
    NIU,
    NLD,
    NOR,
    NPL,
    NRU,
    NZL,
    OMN,
    PAK,
    PAN,
    PCN,
    PER,
    PHL,
    PLW,
    PNG,
    POL,
    PRI,
    PRK,
    PRT,
    PRY,
    PSE,
    PYF,
    QAT,
    REU,
    ROU,
    RUS,
    RWA,
    SAU,
    SDN,
    SEN,
    SGP,
    SGS,
    SHN,
    SJM,
    SLB,
    SLE,
    SLV,
    SMR,
    SOM,
    SPM,
    SRB,
    SSD,
    STP,
    SUR,
    SVK,
    SVN,
    SWE,
    SWZ,
    SXM,
    SYC,
    SYR,
    TCA,
    TCD,
    TGO,
    THA,
    TJK,
    TKL,
    TKM,
    TLS,
    TON,
    TTO,
    TUN,
    TUR,
    TUV,
    TWN,
    TZA,
    UGA,
    UKR,
    UMI,
    URY,
    USA,
    UZB,
    VAT,
    VCT,
    VEN,
    VGB,
    VIR,
    VNM,
    VUT,
    WLF,
    WSM,
    YEM,
    ZAF,
    ZMB,
    ZWE,
}

impl CountryCode {
    pub fn as_str(&self) -> &str {
        match self {
            Self::ABW => "ABW",
            Self::AFG => "AFG",
            Self::AGO => "AGO",
            Self::AIA => "AIA",
            Self::ALA => "ALA",
            Self::ALB => "ALB",
            Self::AND => "AND",
            Self::ARE => "ARE",
            Self::ARG => "ARG",
            Self::ARM => "ARM",
            Self::ASM => "ASM",
            Self::ATA => "ATA",
            Self::ATF => "ATF",
            Self::ATG => "ATG",
            Self::AUS => "AUS",
            Self::AUT => "AUT",
            Self::AZE => "AZE",
            Self::BDI => "BDI",
            Self::BEL => "BEL",
            Self::BEN => "BEN",
            Self::BES => "BES",
            Self::BFA => "BFA",
            Self::BGD => "BGD",
            Self::BGR => "BGR",
            Self::BHR => "BHR",
            Self::BHS => "BHS",
            Self::BIH => "BIH",
            Self::BLM => "BLM",
            Self::BLR => "BLR",
            Self::BLZ => "BLZ",
            Self::BMU => "BMU",
            Self::BOL => "BOL",
            Self::BRA => "BRA",
            Self::BRB => "BRB",
            Self::BRN => "BRN",
            Self::BTN => "BTN",
            Self::BVT => "BVT",
            Self::BWA => "BWA",
            Self::CAF => "CAF",
            Self::CAN => "CAN",
            Self::CCK => "CCK",
            Self::CHE => "CHE",
            Self::CHL => "CHL",
            Self::CHN => "CHN",
            Self::CIV => "CIV",
            Self::CMR => "CMR",
            Self::COD => "COD",
            Self::COG => "COG",
            Self::COK => "COK",
            Self::COL => "COL",
            Self::COM => "COM",
            Self::CPV => "CPV",
            Self::CRI => "CRI",
            Self::CUB => "CUB",
            Self::CUW => "CUW",
            Self::CXR => "CXR",
            Self::CYM => "CYM",
            Self::CYP => "CYP",
            Self::CZE => "CZE",
            Self::DEU => "DEU",
            Self::DJI => "DJI",
            Self::DMA => "DMA",
            Self::DNK => "DNK",
            Self::DOM => "DOM",
            Self::DZA => "DZA",
            Self::ECU => "ECU",
            Self::EGY => "EGY",
            Self::ERI => "ERI",
            Self::ESH => "ESH",
            Self::ESP => "ESP",
            Self::EST => "EST",
            Self::ETH => "ETH",
            Self::FIN => "FIN",
            Self::FJI => "FJI",
            Self::FLK => "FLK",
            Self::FRA => "FRA",
            Self::FRO => "FRO",
            Self::FSM => "FSM",
            Self::GAB => "GAB",
            Self::GBR => "GBR",
            Self::GEO => "GEO",
            Self::GGY => "GGY",
            Self::GHA => "GHA",
            Self::GIB => "GIB",
            Self::GIN => "GIN",
            Self::GLP => "GLP",
            Self::GMB => "GMB",
            Self::GNB => "GNB",
            Self::GNQ => "GNQ",
            Self::GRC => "GRC",
            Self::GRD => "GRD",
            Self::GRL => "GRL",
            Self::GTM => "GTM",
            Self::GUF => "GUF",
            Self::GUM => "GUM",
            Self::GUY => "GUY",
            Self::HKG => "HKG",
            Self::HMD => "HMD",
            Self::HND => "HND",
            Self::HRV => "HRV",
            Self::HTI => "HTI",
            Self::HUN => "HUN",
            Self::IDN => "IDN",
            Self::IMN => "IMN",
            Self::IND => "IND",
            Self::IOT => "IOT",
            Self::IRL => "IRL",
            Self::IRN => "IRN",
            Self::IRQ => "IRQ",
            Self::ISL => "ISL",
            Self::ISR => "ISR",
            Self::ITA => "ITA",
            Self::JAM => "JAM",
            Self::JEY => "JEY",
            Self::JOR => "JOR",
            Self::JPN => "JPN",
            Self::KAZ => "KAZ",
            Self::KEN => "KEN",
            Self::KGZ => "KGZ",
            Self::KHM => "KHM",
            Self::KIR => "KIR",
            Self::KNA => "KNA",
            Self::KOR => "KOR",
            Self::KWT => "KWT",
            Self::LAO => "LAO",
            Self::LBN => "LBN",
            Self::LBR => "LBR",
            Self::LBY => "LBY",
            Self::LCA => "LCA",
            Self::LIE => "LIE",
            Self::LKA => "LKA",
            Self::LSO => "LSO",
            Self::LTU => "LTU",
            Self::LUX => "LUX",
            Self::LVA => "LVA",
            Self::MAC => "MAC",
            Self::MAF => "MAF",
            Self::MAR => "MAR",
            Self::MCO => "MCO",
            Self::MDA => "MDA",
            Self::MDG => "MDG",
            Self::MDV => "MDV",
            Self::MEX => "MEX",
            Self::MHL => "MHL",
            Self::MKD => "MKD",
            Self::MLI => "MLI",
            Self::MLT => "MLT",
            Self::MMR => "MMR",
            Self::MNE => "MNE",
            Self::MNG => "MNG",
            Self::MNP => "MNP",
            Self::MOZ => "MOZ",
            Self::MRT => "MRT",
            Self::MSR => "MSR",
            Self::MTQ => "MTQ",
            Self::MUS => "MUS",
            Self::MWI => "MWI",
            Self::MYS => "MYS",
            Self::MYT => "MYT",
            Self::NAM => "NAM",
            Self::NCL => "NCL",
            Self::NER => "NER",
            Self::NFK => "NFK",
            Self::NGA => "NGA",
            Self::NIC => "NIC",
            Self::NIU => "NIU",
            Self::NLD => "NLD",
            Self::NOR => "NOR",
            Self::NPL => "NPL",
            Self::NRU => "NRU",
            Self::NZL => "NZL",
            Self::OMN => "OMN",
            Self::PAK => "PAK",
            Self::PAN => "PAN",
            Self::PCN => "PCN",
            Self::PER => "PER",
            Self::PHL => "PHL",
            Self::PLW => "PLW",
            Self::PNG => "PNG",
            Self::POL => "POL",
            Self::PRI => "PRI",
            Self::PRK => "PRK",
            Self::PRT => "PRT",
            Self::PRY => "PRY",
            Self::PSE => "PSE",
            Self::PYF => "PYF",
            Self::QAT => "QAT",
            Self::REU => "REU",
            Self::ROU => "ROU",
            Self::RUS => "RUS",
            Self::RWA => "RWA",
            Self::SAU => "SAU",
            Self::SDN => "SDN",
            Self::SEN => "SEN",
            Self::SGP => "SGP",
            Self::SGS => "SGS",
            Self::SHN => "SHN",
            Self::SJM => "SJM",
            Self::SLB => "SLB",
            Self::SLE => "SLE",
            Self::SLV => "SLV",
            Self::SMR => "SMR",
            Self::SOM => "SOM",
            Self::SPM => "SPM",
            Self::SRB => "SRB",
            Self::SSD => "SSD",
            Self::STP => "STP",
            Self::SUR => "SUR",
            Self::SVK => "SVK",
            Self::SVN => "SVN",
            Self::SWE => "SWE",
            Self::SWZ => "SWZ",
            Self::SXM => "SXM",
            Self::SYC => "SYC",
            Self::SYR => "SYR",
            Self::TCA => "TCA",
            Self::TCD => "TCD",
            Self::TGO => "TGO",
            Self::THA => "THA",
            Self::TJK => "TJK",
            Self::TKL => "TKL",
            Self::TKM => "TKM",
            Self::TLS => "TLS",
            Self::TON => "TON",
            Self::TTO => "TTO",
            Self::TUN => "TUN",
            Self::TUR => "TUR",
            Self::TUV => "TUV",
            Self::TWN => "TWN",
            Self::TZA => "TZA",
            Self::UGA => "UGA",
            Self::UKR => "UKR",
            Self::UMI => "UMI",
            Self::URY => "URY",
            Self::USA => "USA",
            Self::UZB => "UZB",
            Self::VAT => "VAT",
            Self::VCT => "VCT",
            Self::VEN => "VEN",
            Self::VGB => "VGB",
            Self::VIR => "VIR",
            Self::VNM => "VNM",
            Self::VUT => "VUT",
            Self::WLF => "WLF",
            Self::WSM => "WSM",
            Self::YEM => "YEM",
            Self::ZAF => "ZAF",
            Self::ZMB => "ZMB",
            Self::ZWE => "ZWE",
        }
    }

    pub fn as_name(&self) -> &str {
        match self {
            Self::ABW => "Aruba",
            Self::AFG => "Afghanistan",
            Self::AGO => "Angola",
            Self::AIA => "Anguilla",
            Self::ALA => "Åland Islands",
            Self::ALB => "Albania",
            Self::AND => "Andorra",
            Self::ARE => "United Arab Emirates",
            Self::ARG => "Argentina",
            Self::ARM => "Armenia",
            Self::ASM => "American Samoa",
            Self::ATA => "Antarctica",
            Self::ATF => "French Southern Territories",
            Self::ATG => "Antigua and Barbuda",
            Self::AUS => "Australia",
            Self::AUT => "Austria",
            Self::AZE => "Azerbaijan",
            Self::BDI => "Burundi",
            Self::BEL => "Belgium",
            Self::BEN => "Benin",
            Self::BES => "Bonaire, Sint Eustatius and Saba",
            Self::BFA => "Burkina Faso",
            Self::BGD => "Bangladesh",
            Self::BGR => "Bulgaria",
            Self::BHR => "Bahrain",
            Self::BHS => "Bahamas",
            Self::BIH => "Bosnia and Herzegovina",
            Self::BLM => "Saint Barthélemy",
            Self::BLR => "Belarus",
            Self::BLZ => "Belize",
            Self::BMU => "Bermuda",
            Self::BOL => "Bolivia, Plurinational State of",
            Self::BRA => "Brazil",
            Self::BRB => "Barbados",
            Self::BRN => "Brunei Darussalam",
            Self::BTN => "Bhutan",
            Self::BVT => "Bouvet Island",
            Self::BWA => "Botswana",
            Self::CAF => "Central African Republic",
            Self::CAN => "Canada",
            Self::CCK => "Cocos (Keeling) Islands",
            Self::CHE => "Switzerland",
            Self::CHL => "Chile",
            Self::CHN => "China",
            Self::CIV => "Côte d'Ivoire",
            Self::CMR => "Cameroon",
            Self::COD => "Congo, Democratic Republic of the",
            Self::COG => "Congo",
            Self::COK => "Cook Islands",
            Self::COL => "Colombia",
            Self::COM => "Comoros",
            Self::CPV => "Cabo Verde",
            Self::CRI => "Costa Rica",
            Self::CUB => "Cuba",
            Self::CUW => "Curaçao",
            Self::CXR => "Christmas Island",
            Self::CYM => "Cayman Islands",
            Self::CYP => "Cyprus",
            Self::CZE => "Czechia",
            Self::DEU => "Germany",
            Self::DJI => "Djibouti",
            Self::DMA => "Dominica",
            Self::DNK => "Denmark",
            Self::DOM => "Dominican Republic",
            Self::DZA => "Algeria",
            Self::ECU => "Ecuador",
            Self::EGY => "Egypt",
            Self::ERI => "Eritrea",
            Self::ESH => "Western Sahara",
            Self::ESP => "Spain",
            Self::EST => "Estonia",
            Self::ETH => "Ethiopia",
            Self::FIN => "Finland",
            Self::FJI => "Fiji",
            Self::FLK => "Falkland Islands (Malvinas)",
            Self::FRA => "France",
            Self::FRO => "Faroe Islands",
            Self::FSM => "Micronesia, Federated States of",
            Self::GAB => "Gabon",
            Self::GBR => "United Kingdom of Great Britain and Northern Ireland",
            Self::GEO => "Georgia",
            Self::GGY => "Guernsey",
            Self::GHA => "Ghana",
            Self::GIB => "Gibraltar",
            Self::GIN => "Guinea",
            Self::GLP => "Guadeloupe",
            Self::GMB => "Gambia",
            Self::GNB => "Guinea-Bissau",
            Self::GNQ => "Equatorial Guinea",
            Self::GRC => "Greece",
            Self::GRD => "Grenada",
            Self::GRL => "Greenland",
            Self::GTM => "Guatemala",
            Self::GUF => "French Guiana",
            Self::GUM => "Guam",
            Self::GUY => "Guyana",
            Self::HKG => "Hong Kong",
            Self::HMD => "Heard Island and McDonald Islands",
            Self::HND => "Honduras",
            Self::HRV => "Croatia",
            Self::HTI => "Haiti",
            Self::HUN => "Hungary",
            Self::IDN => "Indonesia",
            Self::IMN => "Isle of Man",
            Self::IND => "India",
            Self::IOT => "British Indian Ocean Territory",
            Self::IRL => "Ireland",
            Self::IRN => "Iran, Islamic Republic of",
            Self::IRQ => "Iraq",
            Self::ISL => "Iceland",
            Self::ISR => "Israel",
            Self::ITA => "Italy",
            Self::JAM => "Jamaica",
            Self::JEY => "Jersey",
            Self::JOR => "Jordan",
            Self::JPN => "Japan",
            Self::KAZ => "Kazakhstan",
            Self::KEN => "Kenya",
            Self::KGZ => "Kyrgyzstan",
            Self::KHM => "Cambodia",
            Self::KIR => "Kiribati",
            Self::KNA => "Saint Kitts and Nevis",
            Self::KOR => "Korea, Republic of",
            Self::KWT => "Kuwait",
            Self::LAO => "Lao People's Democratic Republic",
            Self::LBN => "Lebanon",
            Self::LBR => "Liberia",
            Self::LBY => "Libya",
            Self::LCA => "Saint Lucia",
            Self::LIE => "Liechtenstein",
            Self::LKA => "Sri Lanka",
            Self::LSO => "Lesotho",
            Self::LTU => "Lithuania",
            Self::LUX => "Luxembourg",
            Self::LVA => "Latvia",
            Self::MAC => "Macao",
            Self::MAF => "Saint Martin (French part)",
            Self::MAR => "Morocco",
            Self::MCO => "Monaco",
            Self::MDA => "Moldova, Republic of",
            Self::MDG => "Madagascar",
            Self::MDV => "Maldives",
            Self::MEX => "Mexico",
            Self::MHL => "Marshall Islands",
            Self::MKD => "North Macedonia",
            Self::MLI => "Mali",
            Self::MLT => "Malta",
            Self::MMR => "Myanmar",
            Self::MNE => "Montenegro",
            Self::MNG => "Mongolia",
            Self::MNP => "Northern Mariana Islands",
            Self::MOZ => "Mozambique",
            Self::MRT => "Mauritania",
            Self::MSR => "Montserrat",
            Self::MTQ => "Martinique",
            Self::MUS => "Mauritius",
            Self::MWI => "Malawi",
            Self::MYS => "Malaysia",
            Self::MYT => "Mayotte",
            Self::NAM => "Namibia",
            Self::NCL => "New Caledonia",
            Self::NER => "Niger",
            Self::NFK => "Norfolk Island",
            Self::NGA => "Nigeria",
            Self::NIC => "Nicaragua",
            Self::NIU => "Niue",
            Self::NLD => "Netherlands, Kingdom of the",
            Self::NOR => "Norway",
            Self::NPL => "Nepal",
            Self::NRU => "Nauru",
            Self::NZL => "New Zealand",
            Self::OMN => "Oman",
            Self::PAK => "Pakistan",
            Self::PAN => "Panama",
            Self::PCN => "Pitcairn",
            Self::PER => "Peru",
            Self::PHL => "Philippines",
            Self::PLW => "Palau",
            Self::PNG => "Papua New Guinea",
            Self::POL => "Poland",
            Self::PRI => "Puerto Rico",
            Self::PRK => "Korea, Democratic People's Republic of",
            Self::PRT => "Portugal",
            Self::PRY => "Paraguay",
            Self::PSE => "Palestine, State of",
            Self::PYF => "French Polynesia",
            Self::QAT => "Qatar",
            Self::REU => "Réunion",
            Self::ROU => "Romania",
            Self::RUS => "Russian Federation",
            Self::RWA => "Rwanda",
            Self::SAU => "Saudi Arabia",
            Self::SDN => "Sudan",
            Self::SEN => "Senegal",
            Self::SGP => "Singapore",
            Self::SGS => "South Georgia and the South Sandwich Islands",
            Self::SHN => "Saint Helena, Ascension and Tristan da Cunha",
            Self::SJM => "Svalbard and Jan Mayen",
            Self::SLB => "Solomon Islands",
            Self::SLE => "Sierra Leone",
            Self::SLV => "El Salvador",
            Self::SMR => "San Marino",
            Self::SOM => "Somalia",
            Self::SPM => "Saint Pierre and Miquelon",
            Self::SRB => "Serbia",
            Self::SSD => "South Sudan",
            Self::STP => "Sao Tome and Principe",
            Self::SUR => "Suriname",
            Self::SVK => "Slovakia",
            Self::SVN => "Slovenia",
            Self::SWE => "Sweden",
            Self::SWZ => "Eswatini",
            Self::SXM => "Sint Maarten (Dutch part)",
            Self::SYC => "Seychelles",
            Self::SYR => "Syrian Arab Republic",
            Self::TCA => "Turks and Caicos Islands",
            Self::TCD => "Chad",
            Self::TGO => "Togo",
            Self::THA => "Thailand",
            Self::TJK => "Tajikistan",
            Self::TKL => "Tokelau",
            Self::TKM => "Turkmenistan",
            Self::TLS => "Timor-Leste",
            Self::TON => "Tonga",
            Self::TTO => "Trinidad and Tobago",
            Self::TUN => "Tunisia",
            Self::TUR => "Türkiye",
            Self::TUV => "Tuvalu",
            Self::TWN => "Taiwan, Province of China",
            Self::TZA => "Tanzania, United Republic of",
            Self::UGA => "Uganda",
            Self::UKR => "Ukraine",
            Self::UMI => "United States Minor Outlying Islands",
            Self::URY => "Uruguay",
            Self::USA => "United States of America",
            Self::UZB => "Uzbekistan",
            Self::VAT => "Holy See",
            Self::VCT => "Saint Vincent and the Grenadines",
            Self::VEN => "Venezuela, Bolivarian Republic of",
            Self::VGB => "Virgin Islands (British)",
            Self::VIR => "Virgin Islands (U.S.)",
            Self::VNM => "Viet Nam",
            Self::VUT => "Vanuatu",
            Self::WLF => "Wallis and Futuna",
            Self::WSM => "Samoa",
            Self::YEM => "Yemen",
            Self::ZAF => "South Africa",
            Self::ZMB => "Zambia",
            Self::ZWE => "Zimbabwe",
        }
    }
}
